### ISSUE TITLE
Flipper Crashes when not in use.

### ISSUE THREAD

**Issue by alessiodam** [RogueMaster/flipperzero-firmware-wPlugins#717]
### Describe the bug.

When I don't use my flipper anymore, after a while, it crashes and reboots.
The error message as follows:
Flipper Crashed and Rebooted
ST(R) GoPro(R) HardFault

### Reproduction

1. Switch on
2. Don't use it for a while
3. Look at the screen after about 6-7h

### Target

0.87.1[19-07-2023]

**Comment by mriliu** [comment]
Same problem

**Comment by RogueMaster** [comment]
Yes this is a known issue with sleep mode that OFW is working on. For the time being, set you sleep mode to Legacy to avoid it

**Comment by alessiodam** [comment]
Ok, I just updated my flipper with the RM firmware (latest) and it was fixed, so idk 🤷

**Comment by mriliu** [comment]
Weird, I have the latest firmware and it still happened for me.

**Comment by RogueMaster** [comment]
It's still there, nobody fixed it yet. Set you sleep mode to Legacy to avoid it.

**Comment by alessiodam** [comment]
ok, thanks
